/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
package ui.test {
	import laya.ui.*;
	import laya.display.*;
	import script.GameUI;

	public class TestSceneUI extends Scene {
		public var promptLabel:Label;
		public var mainView:Sprite;
		public var regBtn:Button;
		public var login2Btn:Button;
		public var betBtn:Button;
		public var minTI:TextInput;
		public var maxTI:TextInput;
		public var regView:Sprite;
		public var passwd:TextInput;
		public var repasswd:TextInput;
		public var backBtn:Button;
		public var createBtn:Button;
		public var nep2key:TextInput;
		public var wif:TextInput;
		public var wifLoginView:Sprite;
		public var wif1:TextInput;
		public var wifLoginBtn:Button;
		public var wifLoginState:Label;
		public var backFromWifBtn:Button;
		public var neoGasLabel:Label;
		public var nep5Label:Label;
		public var curAddrLabel:Label;
		public var curAddrTI:TextInput;

		override protected function createChildren():void {
			super.createChildren();
			loadScene("test/TestScene");

		}

	}
}